### ISSUE TITLE
Add support for range queries

### ISSUE THREAD

**Issue by valencik** [cozydev-pink/lucille#11]
> name:[Jones TO Smith]
> inclusive range; selects documents whose name field has any value between Jones and Smith, including boundaries.
> 
> score:{2.5 TO 7.3}
> exclusive range; selects documents whose score field is between 2.5 and 7.3, excluding boundaries.
> 
> score:{2.5 TO *]
> one-sided range; selects documents whose score field is larger than 2.5. 

https://lucene.apache.org/core/9_4_2/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html

These examples are actually already in [StandardQueryParserDocsSuite](https://github.com/cozydev-pink/lucille/blob/main/core/src/test/scala/io/pig/lucille/StandardQueryParserDocsSuite.scala#L185-L198) as failing tests.

**Comment by valencik** [comment]
This maybe involves a bit of an investigation on how to design the "range" type. Here's Lucene's: [RangeQueryNode](https://github.com/apache/lucene/blob/main/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/nodes/RangeQueryNode.java)

So that might look something like:
```scala
case class RangeQ[A](lower: A, upper: A, lowerIncl: Boolean, upperIncl: Boolean)
```

I'm not sure if keeping the `A` generic is best or not. It might be nice to know if it's a integer range, or a string range, etc.

**Comment by samspills** [comment]
gonna just use nulls for the bounds, don't worry Andrew :D I got this!

**Comment by valencik** [comment]
We chatted a bit about the data structure to represent the `*` characters and settled on:
```scala
case class RangeQ[A](lower: Option[A], upper: Option[A], lowerIncl: Boolean, upperIncl: Boolean) {
  def hasUpperBound: Boolean = upper.isDefined
}
```

As opposed to something more complex like:
```scala
case class RangeQ[A](lower: A, upper: A, lowerIncl: Boolean, upperIncl: Boolean)
case class UpperRangeQ[A](lower: A, lowerIncl: Boolean, upperIncl: Boolean)
case class LowerRangeQ[A](lower: A, lowerIncl: Boolean, upperIncl: Boolean)
case class Inf(lowerIncl: Boolean, upperIncl: Boolean)
```
