### ISSUE TITLE
Parse `/`

### ISSUE THREAD

**Issue by valencik** [cozydev-pink/lucille#17]
Lucille currently fails to parse something like `fullName:typelevel/fs2`

**Comment by samspills** [comment]
also want to be able to do `name:"cats-effect"` 
- parse `"`
- also name:cats-effect should still work and not do the unary minus situation

**Comment by samspills** [comment]
Is this expected??
<img width="780" alt="image" src="https://user-images.githubusercontent.com/4977741/222003553-dcf8e45e-ff0d-469c-b824-39efdc925401.png">

**Comment by valencik** [comment]
No, I don't think so. I ran into something similar with an Or query.
We'll have to add more tests for these. Thanks for capturing it.

**Comment by valencik** [comment]
QueryAnalyzer fixed the serialization issue, but I don't think we ported over al the query support.
Should be easy to fix
